src/privsep-linux.c: add support for nios2 (#23)
Fix the following build failure:

privsep-linux.c:206:4: error: #error "Platform does not support seccomp filter yet"
 #  error "Platform does not support seccomp filter yet"
    ^~~~~
In file included from privsep-linux.c:36:
privsep-linux.c:213:38: error: 'SECCOMP_AUDIT_ARCH' undeclared here (not in a function); did you mean 'SECCOMP_ALLOW_ARG'?
  BPF_JUMP(BPF_JMP + BPF_JEQ + BPF_K, SECCOMP_AUDIT_ARCH, 1, 0),
                                      ^~~~~~~~~~~~~~~~~~

It should be noted that AUDIT_ARCH_NIOS2 is only defined since kernel
5.2 and
https://github.com/torvalds/linux/commit/1660aac45e5b49a5ace29fb5b73254617533fcbd

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>