src/dhcpcd.c: fix build without fork or signals
Since version 9.3.3 and commit a5348dd02c86fa940cd93f203d0aa974cae0563c,
build without fork or signals fails on:

dhcpcd.c: In function ‘main’:
dhcpcd.c:2261:3: error: label ‘start_master’ used but not defined
   goto start_master;
   ^~~~

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>